services:
  backend:
    image: ghcr.io/christoph-sens/cv-enhancer-be:1.1.1@sha256:4b64efffea6d5f8e272256fafa382066594e2c1104bf9b87ab9430b3b84169a3
    ports:
      - "8080:8080"
    environment:
      OPEN_AI_API_KEY: $OPEN_AI_API_KEY
  frontend:
    image: ghcr.io/christoph-sens/cv-enhancer-fe/cv-enhancer-fe:1.0
    ports:
      - "80:80"