apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/christoph-sens/cv-enhancer-be:1.1.1@sha256:4b64efffea6d5f8e272256fafa382066594e2c1104bf9b87ab9430b3b84169a3
          ports:
            - containerPort: 8080
          env:
            - name: OPEN_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: open-ai-api-key-secret
                  key: OPEN_AI_API_KEY
